name: Release

on:
  push:
    branches:
      - main
      - dev
  
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3.0.0
      with:
        branches: |
          [
            '+([0-9])?(.{+([0-9]),x}).x',
            'master',
          
          ]
        extra_plugins: |
          @semantic-release/git
          @semantic-release/exec
          @semantic-release/changelog