publish:
  needs: [ build ]
  runs-on: ubuntu-latest
steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test Semantic Release
      uses: cycjimmy/semantic-release-action@v3.0.0
      with:
        extra_plugins: |
          @semantic-release/git
          @semantic-release/exec
          @semantic-release/changelog